version: '3.8'

services:
mongodb:
image: mongo:latest
container_name: mongodb_chat
ports:
- "27017:27017"
volumes:
- mongodb_data:/data/db
networks:
- chat_network

app:
build:
context: .
dockerfile: Dockerfile
container_name: chat_app
ports:
- "8080:8080" # Порт вашого Fiber-додатку
depends_on:
- mongodb
environment: # Змінні середовища для додатку
PORT: 8080
MONGODB_URI: mongodb://mongodb:27017 # Ім'я сервісу "mongodb" як hostname
MONGODB_NAME: chatdb
JWT_SECRET: supersecretjwtkey # Змініть на щось складніше
ACCESS_TOKEN_TTL: 3600 # 1 година
REFRESH_TOKEN_TTL: 2592000 # 30 днів
networks:
- chat_network
restart: always

networks:
chat_network:
driver: bridge

volumes:
mongodb_data: # Том для збереження даних MongoDB